language: python
script: tox -e repo-test
jobs:
  include:

    - name: "Python 3.6 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.6
      before_install:
        - python3 --version
        - python3 -m pip install tox-travis
